use_default=r"No"
default_engine=r"None"
image_search_engine_link=r"https://hubblesite.org/resource-gallery/images#{}"
image_class=r"text-overlay__img"
nextpage_or_scrolldown=1
scrolldown_times=5
how_many_pages=r"None"
next_page_css_or_xpath=0
next_page_css_selector=""
next_page_xpath=r"//*[@id=\"section-filter-listing-results-66dc75a4-522d-42ab-aa91-2a6edb594951\"]/div/nav/span[4]/a"
run_js_when_next_page=0
what_js=""
thread=0
chrome_driver_path=r"./chromedriver"
save_path=r"./image"
task="Html"
